apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-ingress"
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "{{ .Values.ingress.clusterIssuer }}"
    nginx.ingress.kubernetes.io/auth-url: "https://{{ .Values.ingress.oauthHost }}/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://{{ .Values.ingress.oauthHost }}/oauth2/start?rd=https%3A%2F%2F$host$request_uri"
spec:
  tls:
  - hosts:
    - "{{ .Values.ingress.domain }}"
    secretName: "{{ .Release.Name }}-tls"
  rules:
  - host: "{{ .Values.ingress.domain }}"
    http:
      paths:
      - backend:
          serviceName: "{{ .Release.Name }}-service"
          servicePort: 80
